context:
  name: pypalettes
  version: "0.1.5"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: fb114a0b8bf92125d3e9068d69fa8b6509fba84b758faae7d8303f475a8b7e31

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.10.0, <4.0

tests:
  - python:
      imports:
        - pypalettes
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pytest
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest >=8.3.4
        - pandas >=2.2.3
    files:
      source:
        - /tests

about:
  homepage: https://python-graph-gallery.com/color-palette-finder/
  summary: 'A large (+2500) collection of color maps for Python.'
  description: |
    A large (+2500) collection of color maps for Python.
    All available palettes can be found in the Color Palette Finder.
    To learn more about how to use pypalettes, please refer to the official documentation.
  license: GPL-3.0-only
  license_file: LICENSE.note
  repository: https://github.com/JosephBARBIERDARNAL/pypalettes
  documentation: https://python-graph-gallery.com/introduction-to-pypalettes/

extra:
  recipe-maintainers:
    - JosephBARBIERDARNAL
    - claudiushaag
