context:
  name: pypalettes
  version: "0.1.6"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c11a2e0d45de7c4333c602e49209807e62d88226f2b777ad47f584256c5c0cbe

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.10.0, <4.0

tests:
  - python:
      imports:
        - pypalettes
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://python-graph-gallery.com/color-palette-finder/
  summary: 'A large (+2500) collection of color maps for Python.'
  description: |
    A large (+2500) collection of color maps for Python.
    All available palettes can be found in the Color Palette Finder.
    To learn more about how to use pypalettes, please refer to the official documentation.
  license: GPL-3.0-only
  license_file: LICENSE.note
  repository: https://github.com/JosephBARBIERDARNAL/pypalettes
  documentation: https://python-graph-gallery.com/introduction-to-pypalettes/

extra:
  recipe-maintainers:
    - JosephBARBIERDARNAL
    - claudiushaag
